<?php

namespace BdeReventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends EntityRepository
{
    /**
     * @return Type
     */
    public function getInvitedType()
    {
        return $this->findOneBy(array('name' => 'Invité'));
    }

    public function getGraduateType()
    {
        return $this->findOneBy(array('name' => 'Diplomé'));
    }
}
